version: '3.8'

services:
  app:
    build: .
    container_name: laravel_vue_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8000/"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: pti
      DB_USERNAME: root
      DB_PASSWORD: ""

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: pti
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:18
    container_name: node_vue
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["npm", "install"]

volumes:
  mysql_data:
